name = "ksefbot-api"
main = "worker-api/worker.ts"
compatibility_date = "2026-01-01"

[vars]
ENVIRONMENT = "cloudflare"
# SSO
GOOGLE_AUTH_URL = "https://accounts.google.com/o/oauth2/v2/auth"
GOOGLE_AUTH_TOKEN_URL = "https://oauth2.googleapis.com/token"
GOOGLE_AUTH_USERINFO_URL = "https://openidconnect.googleapis.com/v1/userinfo"
GOOGLE_CALLBACK_URI = "https://ksefbot-api.druizbarbero.workers.dev/sso/google/callback"
# KSeF
KSEF_URL = "https://api.ksef.mf.gov.pl/v2"
KSEF_INVOICE_SCHEMA = "https://assets.local/schemas/KSeFInvoice.avsc"
KSEF_MIN_TIMEOUT = 100
KSEF_MAX_TIMEOUT = 3000
# CEIDG
CEIDG_URL = "https://dane.biznes.gov.pl/api/ceidg/v3"
CEIDG_LOOKUP_SCHEMA = "https://assets.local/schemas/CEIDGLookup.avsc"
# KRS
KRS_SEARCH_URL = "https://wyszukiwarka-krs-api.ms.gov.pl"
KRS_API_URL = "https://api-krs.ms.gov.pl"
KRS_LOOKUP_SCHEMA = "https://assets.local/schemas/KRSLookup.avsc"
# VAT whitelist
VAT_LB_URL = "https://wl-api.mf.gov.pl/api/search/nip"
VAT_LB_LOOKUP_SCHEMA = "https://assets.local/schemas/VATLBLookup.avsc"
# Taxes
DEFAULT_VAT_PERCENTAGE = 23
DEFAULT_TAX_RATE = 12
DEFAULT_HEALTH_INSURANCE_BASE = 5537.18
DEFAULT_HEALTH_INSURANCE_RATE = 9

[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = true

[assets]
binding = "assets"
directory = "./dist"

[[d1_databases]]
binding = "D1"
database_name = "ksef-bot"
database_id = "101428e1-3e1c-479b-a71b-374c1ee24412"
remote = true

[[workflows]]
name = "invoices-backfill"
binding = "BACKFILL_JOB"
class_name = "InvoicesBackfillJob"