name = "ksefbot-whatsapp"
main = "worker-whatsapp/worker.ts"
compatibility_date = "2026-01-01"

[vars]
ENVIRONMENT = "cloudflare"
META_API_VERSION = "v25.0"
WHATSAPP_PHONE_ID = "1316073114919570"

[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = true

[[d1_databases]]
binding = "D1"
database_name = "ksef-bot"
database_id = "101428e1-3e1c-479b-a71b-374c1ee24412"
remote = true