#@no-redirect
@baseUrl = http://localhost:3001
@apiKey = test
@ceidgUrl = https://dane.biznes.gov.pl/api/ceidg/v3
@ceidgApiKey =
@jdgNip = 7272445205
@jdgId = 4BBCA035-90AF-406C-B811-F835FBAA8753
@companyNip = 5170312965

### List sole propietorship in CEIDG by NIP
GET {{ceidgUrl}}/firmy?nip={{jdgNip}}
Accept: application/json
Authorization: Bearer {{ceidgApiKey}}

### List sole propietorship details in CEIDG
GET {{ceidgUrl}}/firma/{{jdgId}}
Accept: application/json
Authorization: Bearer {{ceidgApiKey}}

### List company in CEIDG should fail
GET {{ceidgUrl}}/firmy?nip={{companyNip}}
Accept: application/json
Authorization: Bearer {{ceidgApiKey}}

### List sole propietorship from lookup entrypoint should succeed
GET {{baseUrl}}/gov/ceidg?nip={{jdgNip}}
Accept: application/json
X-API-Key: {{apiKey}}

### List sole propietorship from lookup entrypoint should fail
GET {{baseUrl}}/gov/ceidg?nip={{companyNip}}
Accept: application/json
X-API-Key: {{apiKey}}