{
    "type": "record",
    "name": "KRSLookup",
    "namespace": "pl.gov.krs",
    "doc": "KRS company details response.",
    "fields": [
        {
            "name": "odpis",
            "aliases": ["copy"],
            "type": {
                "type": "record",
                "name": "KRSOdpis",
                "fields": [
                    {
                        "name": "naglowekA",
                        "aliases": ["header"],
                        "type": {
                            "type": "record",
                            "name": "KRSHeader",
                            "fields": [
                                {
                                    "name": "dataRejestracjiWKRS",
                                    "aliases": ["registrationDate"],
                                    "type": ["null", "string"],
                                    "default": null
                                },
                                {
                                    "name": "stanPozycji",
                                    "aliases": ["positionStatus"],
                                    "type": ["null", "int"],
                                    "default": null
                                }
                            ]
                        }
                    },
                    {
                        "name": "dane",
                        "aliases": ["data"],
                        "type": {
                            "type": "record",
                            "name": "KRSData",
                            "fields": [
                                {
                                    "name": "dzial1",
                                    "aliases": ["section1"],
                                    "type": {
                                        "type": "record",
                                        "name": "KRSSection1",
                                        "fields": [
                                            {
                                                "name": "danePodmiotu",
                                                "aliases": ["entityData"],
                                                "type": {
                                                    "type": "record",
                                                    "name": "KRSEntityData",
                                                    "fields": [
                                                        {
                                                            "name": "identyfikatory",
                                                            "aliases": ["identifiers"],
                                                            "type": {
                                                                "type": "record",
                                                                "name": "KRSIdentifiers",
                                                                "fields": [
                                                                    {
                                                                        "name": "nip",
                                                                        "aliases": ["nip"],
                                                                        "type": "string"
                                                                    },
                                                                    {
                                                                        "name": "regon",
                                                                        "aliases": ["regon"],
                                                                        "type": ["null", "string"],
                                                                        "default": null
                                                                    }
                                                                ]
                                                            }
                                                        },
                                                        {
                                                            "name": "nazwa",
                                                            "aliases": ["name"],
                                                            "type": "string"
                                                        }
                                                    ]
                                                }
                                            },
                                            {
                                                "name": "siedzibaIAdres",
                                                "aliases": ["registeredOfficeAndAddress"],
                                                "type": {
                                                    "type": "record",
                                                    "name": "KRSRegisteredOfficeAndAddress",
                                                    "fields": [
                                                        {
                                                            "name": "adres",
                                                            "aliases": ["address"],
                                                            "type": {
                                                                "type": "record",
                                                                "name": "KRSAddress",
                                                                "fields": [
                                                                    {
                                                                        "name": "miejscowosc",
                                                                        "aliases": ["city"],
                                                                        "type": ["null", "string"],
                                                                        "default": null
                                                                    },
                                                                    {
                                                                        "name": "kodPocztowy",
                                                                        "aliases": ["postalCode"],
                                                                        "type": ["null", "string"],
                                                                        "default": null
                                                                    },
                                                                    {
                                                                        "name": "ulica",
                                                                        "aliases": ["street"],
                                                                        "type": ["null", "string"],
                                                                        "default": null
                                                                    },
                                                                    {
                                                                        "name": "nrDomu",
                                                                        "aliases": ["buildingNumber"],
                                                                        "type": ["null", "string"],
                                                                        "default": null
                                                                    },
                                                                    {
                                                                        "name": "nrLokalu",
                                                                        "aliases": ["apartmentNumber"],
                                                                        "type": ["null", "string"],
                                                                        "default": null
                                                                    },
                                                                    {
                                                                        "name": "kraj",
                                                                        "aliases": ["country"],
                                                                        "type": ["null", "string"],
                                                                        "default": null,
                                                                        "x-enum": {
                                                                            "POLSKA": "PL"
                                                                        }
                                                                    }
                                                                ]
                                                            }
                                                        },
                                                        {
                                                            "name": "adresDoDoreczenElektronicznychWpisanyDoBAE",
                                                            "aliases": ["electronicDeliveryAddress"],
                                                            "type": ["null", "string"],
                                                            "default": null
                                                        }
                                                    ]
                                                }
                                            }
                                        ]
                                    }
                                }
                            ]
                        }
                    }
                ]
            }
        }
    ]
}