#@no-redirect
@baseUrl = http://localhost:3001
@apiKey = test
@from = 2026-07-01
@to = 2026-08-01

### List all
GET {{baseUrl}}/app/taxes
Content-Type: application/json
X-API-Key: {{apiKey}}

### List non-existing tax record
GET {{baseUrl}}/app/taxes?from=missing&to=missing
Content-Type: application/json
X-API-Key: {{apiKey}}

### List existing tax record
GET {{baseUrl}}/app/taxes?from={{from}}&to={{to}}
Content-Type: application/json
X-API-Key: {{apiKey}}