#@no-redirect
@baseUrl = http://localhost:3001
@apiKey = test

### Create tax record for the first time
POST {{baseUrl}}/app/taxes
Content-Type: application/json
X-API-Key: {{apiKey}}

< ../../../testresources/taxes/tax-record-1.json

### Second create attempt whould trigger PK violation error
POST {{baseUrl}}/app/taxes
Content-Type: application/json
X-API-Key: {{apiKey}}

< ../../../testresources/taxes/tax-record-1.json