#@no-redirect
@baseUrl = http://localhost:3001
@apiKey = test
@from = 2026-07-01
@to = 2026-08-01

### Update a missing tax record
PUT {{baseUrl}}/app/taxes
Content-Type: application/json
X-API-Key: {{apiKey}}

{ "from": "missing", "to": "missing", "notes": "nevermind" }

### Update existing tax record
PUT {{baseUrl}}/app/taxes
Content-Type: application/json
X-API-Key: {{apiKey}}

{ "from": "{{from}}", "to": "{{to}}", "notes": "edited" }