#@no-redirect
@baseUrl = https://ksefbot-whatsapp.druizbarbero.workers.dev
@verifyToken =

@metaUrl = https://graph.facebook.com
@apiVersion = v26.0
@accessToken =
@wabaId = 1814174903356359
@mediaId = 1768883360984354
@mediaUrl = https://lookaside.fbsbx.com/whatsapp_business/attachments/?mid=1768883360984354&source=getMedia&ext=1789928589&hash=ATxmIjh0jCxA5Wu7t53BEZW6gKFiBL-SjaA1BoIr72fCiQ

@phoneNumberId = 1212895211918077

### WhatsApp webhook verification
GET {{baseUrl}}/whatsapp/webhooks?hub.mode=subscribe&hub.verify_token={{verifyToken}}&hub.challenge=12345

### Check subscribed apps
GET {{metaUrl}}/{{apiVersion}}/{{wabaId}}/subscribed_apps
Authorization: Bearer {{accessToken}}

### Get Whatsapp media URL
GET {{metaUrl}}/{{apiVersion}}/{{mediaId}}
Authorization: Bearer {{accessToken}}

### Download Whatsapp image
GET {{mediaUrl}}
Authorization: Bearer {{accessToken}}

### Get Whatsapp Flows public key configuration
GET {{metaUrl}}/{{apiVersion}}/{{phoneNumberId}}/whatsapp_business_encryption
Authorization: Bearer {{accessToken}}