#@no-redirect
@baseUrl = https://ksefbot-whatsapp.druizbarbero.workers.dev
@verifyToken =

@metaUrl = https://graph.facebook.com
@apiVersion = v26.0
@accessToken =
@wabaId = 1772724103855526
@mediaId = 1768883360984354
@mediaUrl = https://lookaside.fbsbx.com/whatsapp_business/attachments/?mid=1768883360984354&source=getMedia&ext=1789928589&hash=ATxmIjh0jCxA5Wu7t53BEZW6gKFiBL-SjaA1BoIr72fCiQ

@phoneNumberId = 1316073114919570

### Get Whatsapp Flows public key configuration
GET https://graph.facebook.com/v26.0/me/permissions
Authorization: Bearer {{accessToken}}

### Check subscribed apps
GET {{metaUrl}}/{{apiVersion}}/{{wabaId}}/subscribed_apps
Authorization: Bearer {{accessToken}}

### WhatsApp webhook verification
GET {{baseUrl}}/whatsapp/webhooks?hub.mode=subscribe&hub.verify_token={{verifyToken}}&hub.challenge=12345

### Get Whatsapp media URL
GET {{metaUrl}}/{{apiVersion}}/{{mediaId}}
Authorization: Bearer {{accessToken}}

### Download Whatsapp image
GET {{mediaUrl}}
Authorization: Bearer {{accessToken}}







###
GET https://graph.facebook.com/v26.0/1431639538915116/owned_whatsapp_business_accounts
Authorization: Bearer {{accessToken}}