#@no-redirect
@baseUrl = http://localhost:3001
@apiKey = test

### Submit invoice
POST {{baseUrl}}/ksef/sales
Content-Type: multipart/form-data; boundary=ksefInvoice
X-API-Key: {{apiKey}}

--ksefInvoice
Content-Disposition: form-data; name="file"; filename="september-2026.xml"
Content-Type: application/xml

< ../../../testresources/ksef/sales/september-2026.xml
--ksefInvoice
Content-Disposition: form-data; name="notes"

Test notes
--ksefInvoice--