#@no-redirect
@baseUrl = http://localhost:3001
@apiKey = test
@krsSearchUrl = https://wyszukiwarka-krs-api.ms.gov.pl
@krsApiUrl = https://api-krs.ms.gov.pl
@krsApiKey =
@companyNip = 6252447933
@companyKrs = 0000448939
@jdgNIP = 7272445205

### Find company by NIP in KRS
POST {{krsSearchUrl}}/api/wyszukiwarka/krs
Accept: application/json
Content-Type: application/json
User-Agent: Mozilla/5.0
Apikey: {{krsApiKey}}

{
    "podmiot": {
        "nip": "{{companyNip}}"
    },
    "rejestr": ["P", "S"],
    "paginacja": {}
}

### Find company by KRS number in KRS
GET {{krsApiUrl}}/api/krs/OdpisAktualny/{{companyKrs}}
Accept: application/json

### List sole propietorship in KRS should fail
POST https://wyszukiwarka-krs-api.ms.gov.pl/api/wyszukiwarka/krs
Accept: application/json
Content-Type: application/json
User-Agent: Mozilla/5.0
Apikey: {{krsApiKey}}

{
    "podmiot": {
        "nip": "{{jdgNIP}}"
    },
    "rejestr": ["P", "S"],
    "paginacja": {}
}

### List company from lookup entrypoint should succeed
GET {{baseUrl}}/gov/krs?nip={{companyNip}}
Accept: application/json
X-API-Key: {{apiKey}}

### List sole propietorship from lookup entrypoint should fail
GET {{baseUrl}}/gov/krs?nip={{jdgNIP}}
Accept: application/json
X-API-Key: {{apiKey}}